project_name: grpc_forward_auth

builds:
  - binary: grpc_forward_auth.wasm
    no_unique_dist_dir: true
    main: .
    ldflags:
      - '"-s -w"'
    goos:
      - wasip1 
    goarch:
      - wasm

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^chore:'
      - '^chore(deps):'
      - '^test:'
      - '^tests:'

archives:
  - id: grpc_forward_auth
    name_template: '{{ .ProjectName }}_v{{ .Version }}'
    format: zip
    files:
      - LICENSE
      - .traefik.yml