// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// AuthRequest contains the authentication token
type AuthRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{0}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// AuthResponse contains the authentication result
type AuthResponse struct {
	Allowed              bool              `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{1}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetAllowed() bool {
	if m != nil {
		return m.Allowed
	}
	return false
}

func (m *AuthResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AuthResponse) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthRequest)(nil), "proto.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "proto.AuthResponse")
	proto.RegisterMapType((map[string]string)(nil), "proto.AuthResponse.MetadataEntry")
}

func init() { proto.RegisterFile("proto/auth.proto", fileDescriptor_a9d38a2cdbb4f144) }

var fileDescriptor_a9d38a2cdbb4f144 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x95, 0x56, 0x85, 0xe2, 0x82, 0x54, 0x19, 0x86, 0xa8, 0x53, 0x29, 0x4b, 0xa7, 0xa4,
	0x2d, 0x08, 0x10, 0x88, 0x01, 0x24, 0xd8, 0x58, 0xc2, 0xc6, 0x12, 0x5d, 0x93, 0x23, 0x89, 0x9a,
	0xd8, 0xc1, 0x3e, 0xb7, 0x2a, 0x3f, 0x8e, 0xdf, 0x86, 0x62, 0x37, 0x88, 0x4a, 0x4c, 0x77, 0x4f,
	0xf7, 0xfc, 0xfc, 0xdd, 0xb1, 0x61, 0xad, 0x24, 0xc9, 0x10, 0x0c, 0xe5, 0x81, 0x6d, 0x79, 0xcf,
	0x96, 0xc9, 0x05, 0x1b, 0x3c, 0x1a, 0xca, 0x23, 0xfc, 0x34, 0xa8, 0x89, 0x9f, 0xb1, 0x1e, 0xc9,
	0x15, 0x0a, 0xdf, 0x1b, 0x7b, 0xd3, 0xa3, 0xc8, 0x89, 0xc9, 0xb7, 0xc7, 0x8e, 0x9d, 0x4b, 0xd7,
	0x52, 0x68, 0xe4, 0x3e, 0x3b, 0x84, 0xb2, 0x94, 0x1b, 0x4c, 0xad, 0xb1, 0x1f, 0xb5, 0xb2, 0x99,
	0x54, 0xa8, 0x35, 0x64, 0xe8, 0x77, 0x6c, 0x44, 0x2b, 0xf9, 0x03, 0xeb, 0x57, 0x48, 0x90, 0x02,
	0x81, 0xdf, 0x1d, 0x77, 0xa7, 0x83, 0xc5, 0xb9, 0x43, 0x09, 0xfe, 0x46, 0x07, 0xaf, 0x3b, 0xcf,
	0xb3, 0x20, 0xb5, 0x8d, 0x7e, 0x9f, 0x8c, 0xee, 0xd9, 0xc9, 0xde, 0x88, 0x0f, 0x59, 0x77, 0x85,
	0xdb, 0x1d, 0x68, 0xd3, 0x36, 0xf0, 0x6b, 0x28, 0x4d, 0xfb, 0xb3, 0x13, 0x77, 0x9d, 0x5b, 0x6f,
	0xf1, 0xe2, 0xb6, 0x7c, 0x43, 0xb5, 0x2e, 0x12, 0xe4, 0x37, 0x6e, 0x1d, 0x14, 0x54, 0x24, 0x40,
	0xc8, 0xf9, 0x1e, 0x88, 0xbd, 0xc4, 0xe8, 0xf4, 0x1f, 0xb8, 0xa7, 0xeb, 0xf7, 0xab, 0xac, 0xa0,
	0xdc, 0x2c, 0x83, 0x44, 0x56, 0x61, 0x25, 0xd5, 0x17, 0x88, 0xf9, 0x6c, 0x36, 0x0f, 0x3f, 0xa4,
	0xda, 0x80, 0x4a, 0xe3, 0xe6, 0xc0, 0x71, 0xa6, 0xea, 0x24, 0xae, 0x4b, 0x93, 0x15, 0x22, 0xb4,
	0x21, 0xcb, 0x03, 0x5b, 0x2e, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x47, 0x91, 0xe0, 0x87,
	0x01, 0x00, 0x00,
}
