name: Release

on:
  push:
    tags:
        - "v*.*.*"

jobs:
  main:
    name: Release process
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GO_VERSION: 1.21

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      
      - name: Get dependencies
        run: |
          go mod download

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean --timeout=10m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}